import scrapy
from dateutil import parser
from scrapy.crawler import CrawlerProcess
import sys


# python index.py <start_date> <end_date> <course>
# i.e. python index.py '19 April 2022' '19 April 2022' Epsom
# i.e. python index.py '15 April 2022' '21 April 2022' Cork

class PlacePotSpider(scrapy.Spider):
    name = 'placepot'
    custom_settings = {
        "FEED_URI": "output.csv",
        "FEED_FORMAT": "csv",
    }
    

    def start_requests(self):
        urls = [
            'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/lowara-e-lne-single-stage-in-line-pumps-2-pole',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-pumps',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-accessories',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-break-tanks',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/lowara-e-lne-single-stage-in-line-pumps-2-pole',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-pumps',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-accessories',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-break-tanks',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-flood-kits',
            # 'https://www.anchorpumps.com/manufacturers/anchor-pumps-branded-pumps/anchor-pressurisation-units',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/robusta-drainage-series',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/coronada-submersibles',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/ip-900-submersibles',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/piranha-submersible-grinder-pumps',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/mf-wastewater-submersibles',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/j-c-xj-c-submersibles',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/js-xjs-sludge-pumps',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/sanimax-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/nirolift-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/sanisett-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/piranhamat-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/abs-pumps/sanimat-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/aluminium-blagdon-pumps',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/cast-iron-blagdon-pumps',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/stainless-steel-blagdon-pumps',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/fda-compliant-blagdon-pumps',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/polypropylene-blagdon-pumps',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/pvdf-kynar-blagdon-pumps',
            # 'https://www.anchorpumps.com/manufacturers/blagdon-pumps/accessories',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/gxr-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/gxv25-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/gxv-gxc-m-submersible-waste-water-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/gqs-m-50-series-vortex-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/gqv-m-50-series-vortex-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/geo-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/nce-energy-efficient-circulators',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/mpc-compact-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/nmp-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/easymat-1mx-variable-speed-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/easymat-2mx-variable-speed-twin-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/easymat-3mxh-triple-pump-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/mxh-m-horizontal-multi-stage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/mxh-ei-mxh-f-ei-horizontal-multi-stage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/e-idos-series-pressurised-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/nm-nmd-threaded-end-suction',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/nm-flanged-end-suction',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/nm4-flanged-end-suction',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/n-series-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/n4-series-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/nr-series-inline-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/b-ct-b-t-m-bronze-peripheral-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/t-m-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/ct-m-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/agap-and-medigap-pump-sets',
            # 'https://www.anchorpumps.com/manufacturers/calpeda-pumps/unimat-alpha-pressurisation-set',
            # 'https://www.anchorpumps.com/manufacturers/cat-pumps/cat-plunger-pumps',
            # 'https://www.anchorpumps.com/manufacturers/cat-pumps/cat-piston-pumps',
            # 'https://www.anchorpumps.com/manufacturers/cat-pumps/cat-flush-manifold-pumps',
            # 'https://www.anchorpumps.com/manufacturers/circulating-pumps/se-circulators',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/dab-circulators',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/evo-bronze-range',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/vortex-range',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/evoplus-electra-circulators',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/evoplus-san-circulators',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/genix-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nova-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nova-up-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nova-up-mae-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/dab-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nova-novapond-submersible',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-bvp-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-vs-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-fxv-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-fxc-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-6000-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/feka-8000-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/grinder-fx-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/drenag-fx-submersible-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/fkv-wastewater-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/novair-submerged-aerator',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/novabox-tanks',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/fekabox-tanks',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/e-sybox-range',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/aquajet-inox-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/al-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/alm-alp-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/kl-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/dk-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/cme-dcme-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/cpe-dcpe-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/kl-dk-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/cm-dcm-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/cp-dcp-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/k-ha-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/kc-kcv-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/dp-self-priming-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/jet-self-priming-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/jetinox-self-priming-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/euroinox-multi-stage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/multi-inox-self-priming-multi-stage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/kps-kpf-peripheral-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/aquaprof-rain-water-systems',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/e-swim-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/euroswim-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/europro-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/eurocover-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/prefilter-cast-iron-filters',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nkm-g-nkp-g-swimming-pool-prefilter-compatible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/jetcom-sp-eurocom-sp-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/smart-press-controllers',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/multi-4-multi-stage-salt-water-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nkv-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/nkve-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/kvc-vertical-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/kvcx-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/k-single-impeller-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/ki-single-impeller-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/dab-pumps/k-twin-impeller-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/degee-pumps/domestic-hot-water-circulators',
            # 'https://www.anchorpumps.com/manufacturers/flamco-pumps/flamco-combined-air-dirt-separators',
            # 'https://www.anchorpumps.com/manufacturers/flamco-pumps/flamco-air-separators',
            # 'https://www.anchorpumps.com/manufacturers/flamco-pumps/flamco-dirt-separators',
            # 'https://www.anchorpumps.com/manufacturers/flotec-pumps/flotec-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/flotec-pumps/flotec-compac-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/flotec-pumps/drenox-stainless-steel-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/flotec-pumps/omnia-stainless-steel-vortex-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/flotec-pumps/flotec-pump-accessories',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-sololift2-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-shower-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ups-central-heating-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/upm-underfloor-heating-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/alpha-domestic-heating-products',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ups-d-light-commercial-and-commercial-circulator-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ups-d-upc-d-umc-d-pump-heads-and-terminal-boxes',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna1-single-head-variable-speed-circulators-240v-new',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna1-d-twin-head-circulators-new',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna1-n-fn-stainless-steel-circulators-new',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna3-single-head-circulators-240v-new',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna3-d-twin-head-variable-speed-circulators-new',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna3-f-fn-stainless-steel-circulators-new',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/magna-upe-d-pumps-and-spares',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/comfort-and-ups-upn-hot-water-service-circulators',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/manufacturers-grundfos-pumps-grundfos-scala2-domestic-home-booster-grundfos-scala2-3-45-variable-speed-home-booster',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/home-boosters',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/max-e-boosts',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/hydro-multi-e-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/hydro-mpc-e-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-pressurisation-sets',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/domestic-home-boosters',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/cm-cmb-e-cme-horizontal-multi-stage-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-mq',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-jp4-pumps-and-sets',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-jp5-and-jp6',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-jp6-pumps-and-sets',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/cri-vertical-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/cr-cri-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/cr-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/crie-vertical-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/crie-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/crne-vertical-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/crne-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/crn-cast-iron-s-s-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-crn-stainless-steel-vertical-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/crn-stainless-steel-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/mtr-vertical-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/spk-stainless-steel-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/mth-stainless-steel-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/mta-flanged-mounted-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-nb-single-stage-end-suction',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-nbe-single-stage-end-suction',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-tp-tp-d-e-ed-in-line-pump',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/tpe-tpe-d-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/tpe2-tpe3-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/tp-tp-d-e-ed-bronze-in-line-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/cc-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/kp-submersible-drainage-pumps-110v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/kp-submersible-drainage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ap-submersible-drainage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ap35-b-waste-water-and-sewage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ap50-b-waste-water-and-sewage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/ap-submersible-waste-water-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/seg-wastewater-and-sewage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/sl1-sewage-pumps-with-auto-adapt',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/slv-sewage-pumps-with-auto-adapt',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/pust-sewage-dirty-water-package-stations',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/sb-sba-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-sq-sqe-borehole-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-sp-submersible-borehole-240v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-sp-submersible-borehole-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/grundfos-pressure-vessels-tanks',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/conlift-automatic-condensate-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/novalobe-hygienic-pumps',
            # 'https://www.anchorpumps.com/manufacturers/grundfos-pumps/hygia-hygienic-pumps',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-residue-puddle-pumps-110v-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-rs-submersible-drainage-pumps-110v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-rs-submersible-drainage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-rst-rsth-high-head-drainage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-rs-t-high-flow-propeller-pumps-240v-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-heavy-duty-submersible-pumps-110v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-heavy-duty-submersible-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/jst-standard-high-head-submersible-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-gst-grinder-sewage-pumps-110v-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-gst-submersible-grinder-pumps',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-vortex-sewage-pumps-110v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-vortex-sewage-waste-water-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/jst-sv-vortex-sewage-waste-water-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-sk-sewage-single-channel-cutter-pumps-110v-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/jst-sk-sewage-single-channel-cutter-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-ss-316-stainless-steel-submersible-drainage-pumps-110v-240v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-ss-316-stainless-steel-submersible-drainage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-skss-316-stainless-steel-single-channel-cutter-pumps',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/jst-kzn-kzn-h-l-heavy-duty-sludge-slurry-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/jst-kb-kbh-high-head-heavy-duty-sand-silt-slurry-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/js-pumps/js-guide-rail-sets-for-410-1000-range-2-4',
            # 'https://www.anchorpumps.com/manufacturers/koshin-pumps/koshin-submersible-pumps',
            # 'https://www.anchorpumps.com/manufacturers/koshin-pumps/koshin-diesel-powered-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/koshin-pumps/koshin-clean-black-water-engine-pumps',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-drainer-n-series-dirty-water',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-drainer-n-c-series-aggressive-liquids',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/new-ama-drainer-type-3-dirty-water',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-drainer-type-3-c-series-aggressive-liquid',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-porter-submersible-waste-water-and-sewage-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-porter-submersible-waste-water-and-sewage-pumps-415v',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-porter-submersible-waste-water-and-sewage-cutter-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-porter-submersible-waste-water-and-sewage-cutter-pump-415v',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/ama-porter-pump-accessories',
            # 'https://www.anchorpumps.com/manufacturers/ksb-pumps/hya-rain',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-domestic-circulators',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-pro-bronze-circulators',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-d5-vario-circulators',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-xl-d-xlplus-d-single-and-twin-head-circulators-240v',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-xl-d-twin-head-circulators',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-n-shw-circulators',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-tlchn-stainless-steel-circulators',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-ecocirc-xl-b-xlplus-b-circulators-240v',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-doc-submersibles',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-diwa',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-domo',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-dn',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-dl-gl-submersibles',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-sc-scuba',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-c-series',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-co-solids-handling',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-sh-2-pole-end-suction-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-sh-4-pole-end-suction-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/sho-solids-handling',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-she-series',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-nsc-2-pole-end-suction-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-nsc-4-pole-end-suction-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-sv-vertical-multi-stage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-svh-variable-speed-vertical-multistage-240v',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-svh-variable-speed-vertical-multistage-400v',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-hydrovar-variable-speed-drive-pump-mounted',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-hydrovar-variable-speed-drive-wall-mounted',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-fhe-fhs-series',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-lne-single-stage-in-line-pumps-2-pole',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-lne-single-stage-in-line-pumps-4-pole',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-lnt-twin-stage-in-line-pumps-2-pole',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-lnt-twin-stage-in-line-pumps-4-pole',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-bg-series',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-e-hm-hms-series',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-p-series',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-sp-self-priming-peripheral-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-jet-self-priming-centrifugal-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-versatile-utility-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/pressure-vessels',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-reflex-pressure-vessels',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/presfix-pressurisation-sets',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/smb10-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/smb20-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lowara-pumps/lowara-prefabricated-lifting-stations',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-drum-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-pump-tubes',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-drum-pump-motors',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-drum-pump-sets',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-jesco-dosing-electronic-motor-memdos',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-jesco-dosing-memdos-lb',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-jesco-memdos-smart-diaphragm-dosing-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-jesco-magdos-lb-solenoid-dosing-pumps',
            # 'https://www.anchorpumps.com/manufacturers/lutz-jesco/lutz-jesco-magdos-lp-solenoid-dosing-pumps',
            # 'https://www.anchorpumps.com/manufacturers/march-may/ac-mag-drive-pumps',
            # 'https://www.anchorpumps.com/manufacturers/march-may/te-mag-drive-pumps',
            # 'https://www.anchorpumps.com/manufacturers/mono-pumps/ms-range',
            # 'https://www.anchorpumps.com/manufacturers/mono-pumps/mm-range',
            # 'https://www.anchorpumps.com/manufacturers/mono-pumps/ml-range',
            # 'https://www.anchorpumps.com/manufacturers/mono-pumps/m-range-spares',
            # 'https://www.anchorpumps.com/manufacturers/pentax-pumps/pentax-dp-dpv',
            # 'https://www.anchorpumps.com/manufacturers/pentax-pumps/pentax-dp',
            # 'https://www.anchorpumps.com/manufacturers/pentax-pumps/pentax-dg',
            # 'https://www.anchorpumps.com/manufacturers/pentax-pumps/pentax-dx',
            # 'https://www.anchorpumps.com/manufacturers/prominent-pumps/prominent-beta-solenoid',
            # 'https://www.anchorpumps.com/manufacturers/prominent-pumps/prominent-gamma-x-solenoid',
            # 'https://www.anchorpumps.com/manufacturers/prominent-pumps/prominent-delta-solenoid',
            # 'https://www.anchorpumps.com/manufacturers/prominent-pumps/prominent-sigma-metering-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-ct-xtra-shower-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-ct-force-shower-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-right-shower-home-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-ct-bathroom-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-right-rgp-rhp-rsp-shower-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-esp-shower-pumps',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-home-boost',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-eve',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-accuboost',
            # 'https://www.anchorpumps.com/manufacturers/salamander-pumps/salamander-accessories',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-domestic-range',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-professional-range',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-sanifos-range',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-condensate-pumps',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-accessories',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-previous-models',
            # 'https://www.anchorpumps.com/manufacturers/saniflo/saniflo-clearance',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/monsoon-super-silent-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/new-showermate-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/showermate-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/showermate-eco-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/techflo-whisper-quiet-shower-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-circulating-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/pulse-cast-iron-single-head-circulator',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/pulse-cast-iron-twin-head-circulators',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/pulse-bronze-secondary-circulators',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-underfloor-heating-mixers',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/flomate-mains-pressure-booster-pump-240v',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/mainsboost-variq',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/flomate-iboost-compact-home-booster',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-ph-peripheral-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-cast-iron-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/supersub-and-diver-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/jet-booster-pumps-240v',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/ch-ch-fl-ch-b-horizontal-multi-stage-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/ph-ts-fl-b-s-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/es-fl-b-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/wasteflo-domestic-sanitary-pumps',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/bc3-boiler-condensate-pump',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/aquaboost-ch-jet-range',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/aquaboost-ibolt-variable-speed-booster-pump',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/aquaboost-imatic-range1',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/aquaboost-imatic-range',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/aquaboost-abf-range',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/horizontal-variable-speed-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/vertical-variable-speed-booster-sets',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/mainsboost-single-vessels',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/mainsboost-twin-vessels',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/mainsboost-triple-vessels',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/mainsboost-horizontal-vessels',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/mainsboost-plus-pump-single-vessel',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-turner-pressurisation',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/water-conditioners',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-turner-pump-accessories',
            # 'https://www.anchorpumps.com/manufacturers/stuart-turner-pumps/stuart-turner-service-kits',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-pico-range',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-pico-twin',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-maxo-screwed-bsp-range',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-maxo-flanged',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-maxos-twin-range',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/sb-hot-water-circulators',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-maxo-bronze-screwed-bsp-range',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/yonos-maxo-bronze-flanged-range',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/stratos-maxo-range',
            # 'https://www.anchorpumps.com/manufacturers/wilo-pumps/wilo-stratos-maxo-twin-range',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/aluminium',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/cast-iron',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/stainless-steel',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/hygienic',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/fda-compliant',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/polypropylene',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/pvdf-kynar',
            # 'https://www.anchorpumps.com/pump-type/air-operated-diaphragm/accessories',
            # 'https://www.anchorpumps.com/pump-type/booster-pump-sets/grundfos-home-booster-sets',
            # 'https://www.anchorpumps.com/pump-type/booster-pump-sets/stuart-turner-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/booster-pump-sets/lowara-booster-pumps-sets',
            # 'https://www.anchorpumps.com/pump-type/booster-pump-sets/calpeda-easymat-booster-sets',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/grundfos-sqe-variable-speed-energy-efficient-borehole',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/grundfos-sqe-constant-pressure-systems',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/grundfos-sq-submersible-borehole-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/grundfos-sp-submersible-borehole-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/grundfos-sp-submersible-borehole-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/grundfos-sq-sqe-sqflex-accessories',
            # 'https://www.anchorpumps.com/pump-type/borehole-well-pumps/lowara-sc-scuba',
            # 'https://www.anchorpumps.com/pump-type/condensate-pumps/grundfos-condensate-pumps',
            # 'https://www.anchorpumps.com/pump-type/condensate-pumps/saniflo-condensate-pumps',
            # 'https://www.anchorpumps.com/pump-type/condensate-pumps/stuart-turner-condensate-pumps',
            # 'https://www.anchorpumps.com/pump-type/commercial-circulators/commercial-circulators',
            # 'https://www.anchorpumps.com/pump-type/commercial-circulators/variable-speed-circulators',
            # 'https://www.anchorpumps.com/pump-type/commercial-circulators/light-commercial-circulators',
            # 'https://www.anchorpumps.com/pump-type/commercial-circulators/heads-and-terminal-boxes',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/grundfos-domestic-circulators',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/lowara-ecocirc-domestic-circulators',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/dab-evosta-domestic-circulators',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/stuart-turner-circulators',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/wilo-pico-central-heating-pumps',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/stuart-turner-underfloor-heating-mixers',
            # 'https://www.anchorpumps.com/pump-type/domestic-central-heating-products/degee-domestic-circulators',
            # 'https://www.anchorpumps.com/pump-type/domestic-home-boosters/grundfos-domestic-home-boosters',
            # 'https://www.anchorpumps.com/pump-type/domestic-home-boosters/stuart-turner-domestic-home-boosters',
            # 'https://www.anchorpumps.com/pump-type/domestic-home-boosters/salamander-domestic-home-boosters',
            # 'https://www.anchorpumps.com/pump-type/domestic-home-boosters/lowara-domestic-home-boosters',
            # 'https://www.anchorpumps.com/pump-type/dosing-pumps/prominent-dosing-pumps',
            # 'https://www.anchorpumps.com/pump-type/dosing-pumps/lutz-jesco-dosing-pumps',
            # 'https://www.anchorpumps.com/pump-type/drum-pumps/lutz-vario-drum-pumps',
            # 'https://www.anchorpumps.com/pump-type/drum-pumps/lutz-complete-drum-pump-sets',
            # 'https://www.anchorpumps.com/pump-type/drum-pumps/lutz-pump-tubes',
            # 'https://www.anchorpumps.com/pump-type/drum-pumps/lutz-motors-110v',
            # 'https://www.anchorpumps.com/pump-type/drum-pumps/lutz-motors-240v',
            # 'https://www.anchorpumps.com/pump-type/drum-pumps/lutz-motors-air',
            # 'https://www.anchorpumps.com/pump-type/engine-driven-pumps/diesel-powered-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/engine-driven-pumps/honda-powered-clean-black-water-engine-pumps',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/grundfos-comfort-hot-water-service-circulators-240v',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/lowara-ecocirc-n-secondary-hot-water-circulators',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/lowara-tlchn-secondary-hot-water-circulators',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/lowara-ecocirc-pro-bronze-circulators',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/grundfos-upn-and-ups-n-hot-water-circulators-240v',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/grundfos-alpha-hot-water-circulators',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/lowara-ecocirc-xl-b-circulators-240v',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/lowara-ecocirc-xlplus-b-circulators-240v',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/cpl-bronze-circulator-pumps',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/stuart-turner-hot-water-service-circulator',
            # 'https://www.anchorpumps.com/pump-type/hot-water-service-circulators/stuart-pulse-secondary-circulators',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/grundfos-cm-horizontal-multi-stage-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/grundfos-cm-b-e-horizontal-multi-stage-home-booster',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/grundfos-cme-i-horizontal-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/grundfos-cme-i-horizontal-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/grundfos-cme-g-horizontal-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/grundfos-cme-g-horizontal-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/lowara-e-hm-hms-series',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/lowara-c-series-centrifugal-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/stuart-turner-chm-fl-b-horizontal-multi-stage-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/stuart-turner-aquaboost-ibolt-horizontal-booster-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/dab-multi-4-multi-stage-salt-water-pumps',
            # 'https://www.anchorpumps.com/pump-type/horizontal-multi-stage/calpeda-mxh-m-horizontal-multi-stage-pumps',
            # 'https://www.anchorpumps.com/pump-type/hygienic-pumps/grundfos-novalobe-hygienic-pumps',
            # 'https://www.anchorpumps.com/pump-type/hygienic-pumps/grundfos-hygia-hygienic-pumps',
            # 'https://www.anchorpumps.com/pump-type/immersible-pumps/grundfos-mtr-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/immersible-pumps/grundfos-spk-stainless-steel-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/immersible-pumps/grundfos-mth-stainless-steel-immersible-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/immersible-pumps/grundfos-mta-flanged-mounted-immersible-pumps',
            # 'https://www.anchorpumps.com/pump-type/garden-pumps/water-feature-pumps-accessories',
            # 'https://www.anchorpumps.com/pump-type/garden-pumps/garden-hose-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/package-stations/abs-package-pumping-stations',
            # 'https://www.anchorpumps.com/pump-type/package-stations/grundfos-package-pumping-stations',
            # 'https://www.anchorpumps.com/pump-type/package-stations/lowara-package-pumping-stations',
            # 'https://www.anchorpumps.com/pump-type/package-stations/saniflo-package-pumping-stations',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/lowara-p-series-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/lowara-sp-self-priming-peripheral-pumps',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/dab-kps-kpf-peripheral-pumps',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/calpeda-b-t-m-b-ct-m-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/calpeda-t-m-series-peripheral-pumps',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/calpeda-ct-m-peripheral-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/peripheral-booster-pumps/stuart-turner-ph-ts-fl-b-s-es-fl-b-series',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/grundfos-gt-h-and-gt-d-vertical-diaphragm-tanks',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/grundfos-gt-h-horizontal-diaphragm-tanks',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/grundfos-gt-u-cold-water-bladder-tanks',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/grundfos-gt-hr-hot-water-diaphragm-tanks',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/vertical-10-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/horizontal-10-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/lowara-vertical-stainless-steel-10-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/lowara-horizontal-stainless-steel-10-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/vertical-and-horizontal-16-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/lowara-reflex-vertical-10-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/lowara-reflex-horizontal-10-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/lowara-reflex-vertical-16-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/lowara-reflex-vertical-25-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-mainsboost-10-bar-single',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-mainsboost-10-bar-twin',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-mainsboost-10-bar-triple',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-mainsboost-10-bar-horizontal',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-expro-3-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-expro-6-bar',
            # 'https://www.anchorpumps.com/pump-type/pressure-vessels/stuart-turner-expro-10-bar-vertical',
            # 'https://www.anchorpumps.com/pump-type/pressurisation-sets/grundfos-pressurisation-sets',
            # 'https://www.anchorpumps.com/pump-type/pressurisation-sets/lowara-pressurisation-sets',
            # 'https://www.anchorpumps.com/pump-type/pressurisation-sets/unimat-alpha-pressurisation-set',
            # 'https://www.anchorpumps.com/pump-type/pressurisation-sets/agap-pressurisation-sets',
            # 'https://www.anchorpumps.com/pump-type/pressurisation-sets/medigap-pressurisation-set',
            # 'https://www.anchorpumps.com/pump-type/pressurisation-sets/stuart-turner-pressurisation-sets',
            # 'https://www.anchorpumps.com/pump-type/progressive-cavity-pumps/mono-ms-pumps',
            # 'https://www.anchorpumps.com/pump-type/progressive-cavity-pumps/mono-mm-pump-range',
            # 'https://www.anchorpumps.com/pump-type/progressive-cavity-pumps/mono-ml-pump-range',
            # 'https://www.anchorpumps.com/pump-type/progressive-cavity-pumps/mono-m-range-spares',
            # 'https://www.anchorpumps.com/pump-type/rainwater-harvesting/ksb-hya-rain',
            # 'https://www.anchorpumps.com/pump-type/sanitary-pumps/grundfos-sololift2-sanitary-pumps',
            # 'https://www.anchorpumps.com/pump-type/sanitary-pumps/stuart-turner-wasteflo-sanitary-pumps',
            # 'https://www.anchorpumps.com/pump-type/sanitary-pumps/saniflo-domestic-range',
            # 'https://www.anchorpumps.com/pump-type/sanitary-pumps/saniflo-professional-range',
            # 'https://www.anchorpumps.com/pump-type/sanitary-pumps/dab-genix-lifting-stations',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/lowara-bg-bgm-self-priming-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/lowara-jet-pumps',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/lowara-sp-self-priming-peripheral-pumps',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/lowara-versatile-utility-pumps',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/grundfos-jp5',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/grundfos-jp6',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/grundfos-mq',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/grundfos-cm-self-priming-horizontal-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/varisco-self-priming-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/dab-e-sybox',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/mono-cm-series',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/calpeda-mpc-m-nmp-m-series',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/stuart-turner-jet-pumps',
            # 'https://www.anchorpumps.com/pump-type/self-priming-pumps/stuart-turner-ch-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/grundfos-watermill-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/stuart-turner-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/salamander-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/negative-head-single-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/negative-head-twin-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/positive-head-single-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/positive-head-twin-shower-pumps',
            # 'https://www.anchorpumps.com/pump-type/shower-pumps/shower-pump-accessories',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/grundfos-nb-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/lowara-e-nsc-series',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/lowara-e-nsc-4-pole-series',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/lowara-fhe-fhs-series',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/lowara-e-sh-2-pole-end-suction-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/lowara-she-series',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/calpeda-nm-nmd-threaded-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/dab-k-single-impeller-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/dab-ki-single-impeller-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/dab-k-twin-impeller-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/calpeda-nm-flanged-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-end-suction/stuart-turner-kennet-k-kfl-b-end-suction-booster-pumps',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/lowara-e-lne-single-stage-in-line-pumps-2-pole',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/lowara-e-lne-single-stage-in-line-pumps-4-pole',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/lowara-e-lnt-twin-stage-in-line-pumps-2-pole',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/lowara-e-lnt-twin-stage-in-line-pumps-4-pole',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tp-single-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tp-single-head-in-line-4-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tp-single-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tp-single-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-single-head-in-line-6-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tpd-twin-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tpd-twin-head-in-line-4-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tpd-twin-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/tpd-twin-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpd-twin-head-in-line-6-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe2-single-head-in-line-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe2-single-head-in-line-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe2-d-twin-head-in-line-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe2-d-twin-head-in-line-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe3-single-head-in-line-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe3-single-head-in-line-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe3-d-twin-head-in-line-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe3-d-twin-head-in-line-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe-1000-single-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe-1000-single-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe-1000-single-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tped-1000-twin-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tped-1000-twin-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tped-1000-twin-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe-2000-single-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe-2000-single-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe-2000-single-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tped-2000-twin-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tped-2000-twin-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tped-2000-twin-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-stainless-steel-for-hot-water-service-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-stainless-steel-single-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-bronze-single-head-in-line-2-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-bronze-single-head-in-line-2-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-bronze-single-head-in-line-4-pole-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tp-bronze-single-head-in-line-4-pole-415v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe3-stainless-steel-single-head-in-line-240v',
            # 'https://www.anchorpumps.com/pump-type/single-stage-in-line-pumps/grundfos-tpe3-stainless-steel-single-head-in-line-415v',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/lowara-com-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/lowara-co-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/lowara-co4-pumps-415v-4-pole',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/lowara-sho-series',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/lowara-shoe4-series',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/sl1-sewage-pumps-with-auto-adapt',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/slv-sewage-pumps-with-auto-adapt',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/seg-pumps-non-explosion-proof-motor',
            # 'https://www.anchorpumps.com/pump-type/solids-handling-pumps/seg-pumps-explosion-proof-motor',
            # 'https://www.anchorpumps.com/pump-type/submersible-pumps/drainage-submersible-pumps',
            # 'https://www.anchorpumps.com/pump-type/submersible-pumps/waste-water-and-sewage-submersibles',
            # 'https://www.anchorpumps.com/pump-type/submersible-pumps/residue-drainage-puddle-pumps',
            # 'https://www.anchorpumps.com/pump-type/submersible-pumps/hot-water-submersible-drainage-pumps',
            # 'https://www.anchorpumps.com/pump-type/submersible-pumps/submersible-package-sets',
            # 'https://www.anchorpumps.com/pump-type/submersible-pumps/slurry-pumps',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/spa-pump-240v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/spa-pump-415v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/mpc-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/mpc-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/nmp-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/nmp-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/dab-europro-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/dab-eurocover-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/prefilter-cast-iron-filters',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/dab-nkm-g-nkp-g-swimming-pool-prefilter-compatible-pumps',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/dab-jetcom-sp-eurocom-sp-swimming-pool-pumps',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/pentair-swimmey-240v',
            # 'https://www.anchorpumps.com/pump-type/swimming-pool-whirlpool-spa/pentair-swimmey-415v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/cri-vertical-multi-stage-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/cri-vertical-multi-stage-accessories',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/cr-vertical-multi-stage-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/crie-vertical-multi-stage-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/cre-cast-iron-stainless-steel-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/crn-stainless-steel-vertical-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/crn-stainless-steel-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/crne-vertical-multi-stage-pumps-240v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/crne-vertical-multi-stage-pumps-415v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/dab-nkv-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/dab-nkve-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/dab-kvc-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/dab-kvcx-multi-stage-centrifugal-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/lowara-e-sv-vertical-multi-stage-pumps',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/lowara-e-svh-variable-speed-vertical-multistage-240v',
            # 'https://www.anchorpumps.com/pump-type/vertical-multi-stage-pumps/lowara-e-svh-variable-speed-vertical-multistage-400v',
            # 'https://www.anchorpumps.com/pump-accessories/air-dirt-separators/flamco-combined-air-dirt-separators',
            # 'https://www.anchorpumps.com/pump-accessories/air-dirt-separators/flamco-air-separators',
            # 'https://www.anchorpumps.com/pump-accessories/air-dirt-separators/flamco-dirt-separators',
            # 'https://www.anchorpumps.com/pump-accessories/bellows-accessories/screwed-bsp-expansion-joints',
            # 'https://www.anchorpumps.com/pump-accessories/bellows-accessories/flanged-untied-expansion-joints',
            # 'https://www.anchorpumps.com/pump-accessories/bellows-accessories/flanged-tied-expansion-joints',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/control-boxes-for-sp-240v-pumps',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/control-boxes-for-sqe-pumps',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/drop-cables-for-sp-pumps',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/drop-cables-for-sq-e-pumps',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/horizontal-tanks',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/pressure-managers-for-jp5-jp6-cm-sq-pumps',
            # 'https://www.anchorpumps.com/pump-accessories/borehole-pump-accessories/vertical-tanks',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/pressure-regulators',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/unloaders',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/relief-pop-off-valves',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/pulsation-dampeners',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/thermal-valves',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/inlet-pressure-stabilizers',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/lubricants',
            # 'https://www.anchorpumps.com/pump-accessories/cat-pump-accessories/bellhousings',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/baseplates',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/bellows',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/blanking-plates',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/clocks',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/differential-pressure-transducers',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/dongles',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/insulation-kits',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/modules',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/plugs',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/sensors',
            # 'https://www.anchorpumps.com/pump-accessories/heating-circulator-accessories/spacer-kits',
            # 'https://www.anchorpumps.com/pump-accessories/hose/suction-hose',
            # 'https://www.anchorpumps.com/pump-accessories/hose/layflat-hose',
            # 'https://www.anchorpumps.com/pump-accessories/hose/air-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/chemical-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/ducting-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/fire-fighting-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/gas-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/marine-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/material-handling-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/non-toxic-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/oil-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/pvc-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/steam-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/hose/water-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/insulation-kits/magna-insulation-kits',
            # 'https://www.anchorpumps.com/pump-accessories/insulation-kits/tpe2-tpe3-insulation-kits',
            # 'https://www.anchorpumps.com/pump-accessories/lifting-station-accessories/abs-lifting-station-accessories',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/stainless-steel-flexi-hoses',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/3-part-union',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/ball-retaining-valves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/ball-valves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/bolt-clamps',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/brass-plastic-hosetails',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/elbow-male-female',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/footvalves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/gate-valves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/hose-joiners',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/hose-clips',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/in-line-strainer',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/male-plugs',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/nipples',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/non-return-valves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/pressure-relief-valves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/reducer-bush',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/screw-in-filters',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/step-adaptors',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/sockets',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/swift-quick-release-bayonet-fittings',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/swing-check-valves',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/tee-fittings',
            # 'https://www.anchorpumps.com/pump-accessories/metallic-plastic-fittings/tin-can-strainers',
            # 'https://www.anchorpumps.com/pump-accessories/pressure-vessels/grundfos-pressure-vessels',
            # 'https://www.anchorpumps.com/pump-accessories/pressure-vessels/lowara-pressure-vessels',
            # 'https://www.anchorpumps.com/pump-accessories/pressure-vessels/stuart-turner-pressure-vessels',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/blending-valves',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/flanges',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/hoses',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/negative-head-kits',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/non-return-valves',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/pump-mats',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/socket-reducers',
            # 'https://www.anchorpumps.com/pump-accessories/shower-pump-accessories/water-starvation-protection-kits',
            # 'https://www.anchorpumps.com/pump-accessories/submersible-pump-accessories/abs-submersible-pump-accessories',
            # 'https://www.anchorpumps.com/pump-accessories/submersible-pump-accessories/anchor-submersible-pump-accessories',
            # 'https://www.anchorpumps.com/pump-accessories/submersible-pump-accessories/grundfos-submersible-pump-accessories',
            # 'https://www.anchorpumps.com/pump-accessories/submersible-pump-accessories/js-submersible-pump-accessories',
            # 'https://www.anchorpumps.com/pump-accessories/submersible-pump-accessories/lowara-submersible-pump-accessories',
            # 'https://www.anchorpumps.com/pump-accessories/unions-valves-and-flange-sets/grundfos-nb-e-k-ke',
            # 'https://www.anchorpumps.com/pump-accessories/unions-valves-and-flange-sets/grundfos-ups-d-upe-d-tp-d-magna',
            # 'https://www.anchorpumps.com/pump-accessories/unions-valves-and-flange-sets/grundfos-cri',
            # 'https://www.anchorpumps.com/pump-accessories/unions-valves-and-flange-sets/grundfos-crn-e',
            # 'https://www.anchorpumps.com/pump-accessories/unions-valves-and-flange-sets/circulator-and-shower-pumps',
            # 'https://www.anchorpumps.com/pump-accessories/unions-valves-and-flange-sets/lowara-sh',
            # 'https://www.anchorpumps.com/pump-accessories/variable-speed-drives/lowara-hydrovar-pump-mounted',
            # 'https://www.anchorpumps.com/pump-accessories/variable-speed-drives/lowara-hydrovar-wall-mounted',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/vertical-multi-stage-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/single-stage-in-line-end-suction-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/submersible-drainage-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/waste-water-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/horizontal-multi-stage-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/horizontal-self-priming-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/domestic-booster-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/borehole-submersible-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/cooling-immersibles-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/shower-pumps-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/sololift2',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/pump-heads-and-terminal-box-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/booster-set-spares',
            # 'https://www.anchorpumps.com/spares/grundfos-pump-spares/chamber-stack-for-verticle-multistage-spares',
            # 'https://www.anchorpumps.com/spares/lowara-pump-spares/vertical-multi-stage-spares',
            # 'https://www.anchorpumps.com/spares/lowara-pump-spares/lowara-co-com-spares',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-110-g10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-110-q10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-110-b10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-110-f10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-110-k10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-110-p10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-160-g10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-1-180-g10-et-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-120-g10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-120-q10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-120-b10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-120-k10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-120-f10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-120-p10-e-t-m-0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-170-g10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-180-g10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-2-125-g10-et0',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-3-140-g10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-3-140-q10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-3-140-b10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-3-140-k10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je-3-140-f10-et20',
            # 'https://www.anchorpumps.com/spares/varisco-spares/je3-140-p10-et20'
        ]
        for url in urls:
            # print(url)
            yield scrapy.Request(url=url, callback=self.parse_list)

    def parse_list(self, response):
        try:
            productSelector = ".product-info-stock-sku"
            items = response.css(productSelector).getall()
            if len(items) != 0:
                url = response.url
                # mainSelector = "div.product-info-stock-sku div.value::text"
                # subCategorySelector = "div.product-info-stock-sku div.value::text"
                productNameSelector = "div.page-title span.base::text"
                productCodeSelector = "div.product-info-stock-sku div.value::text"
                mrpPriceSelector = "div.product-info-price span.old-price span.price::text"
                priceSelector = "span.special-price span.price::text"
                overviewSelector = "div.product.info.detailed div.product.attribute.description p::text"
                deliverySelector = "#delivery p::text"
                fullDetailHeaderSelector = "#product-attribute-specs-table th::text"
                fullDetailContentSelector = "#product-attribute-specs-table td::text"
                imgURLSelector = "div.c-gallery__thumbs img::attr(src)"
                # variationSelector = "#delivery p::text"
                downloadSelector = "div.product-attachment-container a::attr(href)"

                # mainSelector = "SKU"+ response.css(skuSelector).get()
                # subCategorySelector = "SKU"+ response.css(skuSelector).get()
                productNameSelector = response.css(productNameSelector).get()
                productCode = "SKU: "+ response.css(productCodeSelector).get()
                mrpPrice = "MRRP" + response.css(mrpPriceSelector).get() + " + VAT"
                price = response.css(priceSelector).get()
                overview = response.css(overviewSelector).getall()
                delivery = response.css(deliverySelector).getall()
                fullDetailHeader = response.css(fullDetailHeaderSelector).getall()
                fullDetailContent = response.css(fullDetailContentSelector).getall()
                fullDetail = ""
                fullDetailindex = [-1, -1, -1, -1, -1, -1, -1, -1, -1]
                for i in range(len(fullDetailHeader)):
                    if fullDetailHeader[i] == "Manufacturer":
                        fullDetailindex[0] = i
                    if fullDetailHeader[i] == "Weight":
                        fullDetailindex[1] = i
                    if fullDetailHeader[i] == "Dimensions":
                        fullDetailindex[2] = i
                    if fullDetailHeader[i] == "Motorsize":
                        fullDetailindex[3] = i
                    if fullDetailHeader[i] == "Fullloadcurrent":
                        fullDetailindex[4] = i
                    if fullDetailHeader[i] == "Voltage":
                        fullDetailindex[5] = i
                    if fullDetailHeader[i] == "MaxFlow":
                        fullDetailindex[6] = i
                    if fullDetailHeader[i] == "MaxHead":
                        fullDetailindex[7] = i
                    if fullDetailHeader[i] == "Material":
                        fullDetailindex[8] = i
                    fullDetailHeader[i] = fullDetailHeader[i].strip()
                    fullDetailContent[i] = fullDetailContent[i].strip()
                    fullDetail += f'{fullDetailHeader[i]} : {fullDetailContent[i]}\n'
                imgURL = response.css(imgURLSelector).getall()
                # variation = response.css(variationSelector).get()
                download = response.css(downloadSelector).getall()
                
                yield {
                    "URL": url,
                    "main": "",
                    "Sub Category-1": "",
                    "Sub Category-2": "",
                    "Product Name": "",
                    "Product Code": productCode,
                    "Mrp price": mrpPrice,
                    "Price": price,
                    "Overview & Spec": overview[0],
                    "DELIVERY & RETURNS": delivery[0],
                    "Full details of table content": fullDetail,
                    "Manufacturer": fullDetailContent[fullDetailindex[0]] if fullDetailindex[0] != -1 else "",
                    "Weight": fullDetailContent[fullDetailindex[1]] if fullDetailindex[1] != -1 else "",
                    "Dimensions": fullDetailContent[fullDetailindex[2]] if fullDetailindex[2] != -1 else "",
                    "Motorsize": fullDetailContent[fullDetailindex[3]] if fullDetailindex[3] != -1 else "",
                    "Full load current": fullDetailContent[fullDetailindex[4]] if fullDetailindex[4] != -1 else "",
                    "Voltage": fullDetailContent[fullDetailindex[5]] if fullDetailindex[5] != -1 else "",
                    "Max Flow": fullDetailContent[fullDetailindex[6]] if fullDetailindex[6] != -1 else "",
                    "Max Head": fullDetailContent[fullDetailindex[7]] if fullDetailindex[7] != -1 else "",
                    "Material": fullDetailContent[fullDetailindex[8]] if fullDetailindex[8] != -1 else "",
                    "Image url-1": imgURL[0] if len(imgURL) > 0 else "",
                    "Image url-2": imgURL[1] if len(imgURL) > 1 else "",
                    "Image url-3": imgURL[2] if len(imgURL) > 2 else "",
                    "Image url-4": imgURL[3] if len(imgURL) > 3 else "",
                    "Image url-5": imgURL[4] if len(imgURL) > 4 else "",
                    "Image url-6": imgURL[5] if len(imgURL) > 5 else "",
                    "Image url-7": imgURL[6] if len(imgURL) > 6 else "",
                    "Variation option-1 name": "",
                    "Variation option-2 name": "",
                    "Variation option-1": "",
                    "Variation option-2": "",
                    "Variation option-3": "",
                    "Variation option-4": "",
                    "Variation option-5": "",
                    "Variation option-6": "",
                    "Variation option-7": "",
                    "Variation option-8": "",
                    "Variation option-9": "",
                    "2 variation option-1": "",
                    "3 variation option-1": "",
                    "4 variation option-1": "",
                    "5 variation option-1": "",
                    "6 variation option-1": "",
                    "7 variation option-1": "",
                    "8 variation option-1": "",
                    "9 variation option-1": "",
                    "File Downloads link-1": download[0] if len(download) > 0 else "",
                    "File Downloads link-2": download[1] if len(download) > 1 else "",
                    "File Downloads link-3": download[2] if len(download) > 2 else "",
                    "File Downloads link-4": download[3] if len(download) > 3 else "",
                }
                return
            productSelector = "div.category-intro__heading-inner h1::text"
            subitem = response.css(productSelector).get()

            productSelector = ".page-main a::attr(href)"
            items = response.css(productSelector).getall()
            for item in items:
                if item.find("https:") != -1:
                    yield scrapy.Request(url=item, callback=self.parse_list)
        except Exception as e:
            print("=====>error", e)
        pass

    def getInfo(self, response):
        nameSelector = ".product-meta h1::text"
        skuSelector = ".product-meta__sku-number::text"
        priceSelector = ".price-list span"

        name = response.css(nameSelector).get()
        sku = "SKU"+ response.css(skuSelector).get()
        price = response.css(priceSelector).get().split("</span>")[1]
        yield {
            "Product Name": name,
            "SKU": sku,
            "Price": price,
            "Website name": "https://rckongen.dk/"
        }

    

process = CrawlerProcess()
process.crawl(PlacePotSpider)
process.start()